# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact/main/dbos-config.schema.json

database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  app_db_name: 'hello'
  connectionTimeoutMillis: 3000
  app_db_client: 'knex'
  migrate:
    - npx knex migrate:latest
  rollback:
    - npx knex migrate:rollback
application:
  aws_sqs_configuration: 'aws_config'
  sqs_queue: ${SQS_QUEUE_URL}
  aws_config:
    aws_region: ${AWS_REGION}
    aws_access_key_id: ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
